// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");

function $$eval(_exresion) {
  while(true) {
    var exresion = _exresion;
    switch (exresion.TAG | 0) {
      case /* Value */0 :
          return exresion._0._0;
      case /* If */1 :
          if ($$eval(exresion._0)) {
            _exresion = exresion._1;
            continue ;
          }
          _exresion = exresion._2;
          continue ;
      case /* Eq */2 :
          return Caml_obj.equal($$eval(exresion._0), $$eval(exresion._1));
      case /* Lt */3 :
          return $$eval(exresion._0) < $$eval(exresion._1);
      
    }
  };
}

var Expr = {
  $$eval: $$eval
};

function $$eval$1(s, ac) {
  if (s.TAG !== /* Step */0) {
    return {
            TAG: /* Confirmed */1,
            _0: s._0
          };
  }
  var st = s._0;
  if (typeof ac === "number" || (ac._0 + 1 | 0) < 3) {
    return {
            TAG: /* Step */0,
            _0: st
          };
  } else {
    return {
            TAG: /* Confirmed */1,
            _0: true
          };
  }
}

var Branch = {
  $$eval: $$eval$1
};

exports.Expr = Expr;
exports.Branch = Branch;
/* No side effect */
