// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("rescript/lib/js/caml_int32.js");

function $$eval(term) {
  if (term.TAG === /* Con */0) {
    return term._0;
  } else {
    return Caml_int32.div($$eval(term._0), $$eval(term._1));
  }
}

var Basic = {
  $$eval: $$eval
};

exports.Basic = Basic;
/* No side effect */
