// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");

function $$eval(_a) {
  while(true) {
    var a = _a;
    switch (a.TAG | 0) {
      case /* Value */0 :
          return a._0._0;
      case /* If */1 :
          if ($$eval(a._0)) {
            _a = a._1;
            continue ;
          }
          _a = a._2;
          continue ;
      case /* Eq */2 :
          return Caml_obj.equal($$eval(a._0), $$eval(a._1));
      case /* Lt */3 :
          return $$eval(a._0) < $$eval(a._1);
      
    }
  };
}

exports.$$eval = $$eval;
/* No side effect */
