// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("ava").default;
var GADTExample = require("../return/core/examples/GADTExample.bs.js");

Ava("GADT. expression.", (function (ctx) {
        var f = GADTExample.Expr.$$eval({
              TAG: /* If */1,
              _0: {
                TAG: /* Value */0,
                _0: {
                  TAG: /* Bool */0,
                  _0: true
                }
              },
              _1: {
                TAG: /* Value */0,
                _0: {
                  TAG: /* Int */1,
                  _0: 1
                }
              },
              _2: {
                TAG: /* Value */0,
                _0: {
                  TAG: /* Int */1,
                  _0: 2
                }
              }
            });
        var s = GADTExample.Expr.$$eval({
              TAG: /* Eq */2,
              _0: {
                TAG: /* Value */0,
                _0: {
                  TAG: /* Str */2,
                  _0: "string"
                }
              },
              _1: {
                TAG: /* Value */0,
                _0: {
                  TAG: /* Str */2,
                  _0: "new string"
                }
              }
            });
        ctx.is(f, 1, undefined);
        ctx.is(s, false, undefined);
      }));

/*  Not a pure module */
