// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("ava").default;
var Paper = require("../return/core/examples/Paper.bs.js");
var Caml_js_exceptions = require("rescript/lib/js/caml_js_exceptions.js");

Ava("Paper. Basic eval. Should success.", (function (ctx) {
        var answer = Paper.Basic.$$eval({
              TAG: /* Div */1,
              _0: {
                TAG: /* Div */1,
                _0: {
                  TAG: /* Con */0,
                  _0: 1972
                },
                _1: {
                  TAG: /* Con */0,
                  _0: 2
                }
              },
              _1: {
                TAG: /* Con */0,
                _0: 23
              }
            });
        ctx.is(answer, 42, undefined);
      }));

Ava("Paper. Basic eval. Should fail.", (function (ctx) {
        try {
          Paper.Basic.$$eval({
                TAG: /* Div */1,
                _0: {
                  TAG: /* Con */0,
                  _0: 1
                },
                _1: {
                  TAG: /* Con */0,
                  _0: 0
                }
              });
          return ;
        }
        catch (raw_exn){
          var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
          if (exn.RE_EXN_ID === "Division_by_zero") {
            ctx.is(0, 0, undefined);
            return ;
          }
          throw exn;
        }
      }));

/*  Not a pure module */
